apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-portfolio
  labels:
    app: astro-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: astro-portfolio
  template:
    metadata:
      labels:
        app: astro-portfolio
    spec:
      containers:
      - name: astro-portfolio
        image: himanshu311999/astrojs-portfolio:latest
        ports:
        - containerPort: 4321
        args:
          - "yarn"
          - "run"
          - "dev"
          - "--host"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
