apiVersion: v1
kind: Service
metadata:
  name: astro-portfolio-service
  labels:
    app: astro-portfolio
spec:
  selector:
    app: astro-portfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4321
  type: ClusterIP
